### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bbowman**

### CODE REVIEW

**Comment by bbowman** [comment]
@PatrickFarley

**Comment by bbowman** [comment]
https://github.com/bbowman/project-rome/tree/bbowman-readme shows the new version. Looks like you updated a lot recently and I'd need to update for MSGraph. Thoughts on the table layout instead of just the links?

**Comment by PatrickFarley** [comment]
Thanks, I will get back to you on this shortly

**Comment by bbowman** [comment]
@PatrickFarley updated.

**Comment by PatrickFarley** [comment]
It looks good, but I do have some concerns, let's discuss at Monday's meeting

**Comment by PatrickFarley** [comment]
What do you think about making the "API Docs" column just "Documentation", and then linking to the general platform folders? If we link to the Android/ folder instead of Android/reference%20documentation/, then users will notice the how-to guides as well as reference docs. Same for the Windows/ folder. And these folders all have brief READMEs that will display by default, which will help users find what they're looking for.

**Comment by bbowman** [comment]
seems reasonable. My main concern was keeping everything up to date. By landing people at the folder instead of directly on the content (especially for Windows SDK or MSGraph where we don't directly host the documentation), we introduce another thing to keep in sync / update and most of the content on the README is going to be a duplicate of what the actual page would show/explain. I do like that we'd have the how-to guides have a bit more visibility though. @cmknox thoughts?

**Comment by PatrickFarley** [comment]
I've resolved the conflicts locally and pushed. closing this PR

**Pull request merged**
